name: AzadKonnande - آزادسازی خودکارuu

on:
  workflow_dispatch:

jobs:
  unlock:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      TARGET_BOT_TOKENS: ${{ secrets.TARGET_BOT_TOKENS }}
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: نصب کتابخانه requests
        run: pip install requests

      - name: اجرای آزادکننده
        run: python AZ.py
