name: AzadKonnande - آزادسازی خودکارUU

on:
  workflow_dispatch:          # فقط با کلیک شما اجرا می‌شود

jobs:
  unlock:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      TARGET_BOT_TOKENS: ${{ secrets.TARGET_BOT_TOKENS }}   # توکن‌های ربات‌های مقصد (با کاما جدا شوند)
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: اجرای آزادکننده
        run: python AZ.py
