name: Baaall

on:
  schedule:
    - cron: "0 */6 * * *"        # هر ۶ ساعت
  workflow_dispatch:            # اجرای دستی

# اضافه کردن این بخش برای رفع ارور Node 20 (طبق تصویر گیت‌هاب)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: دریافت کد از مخزن
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: نصب ابزارهای صوتی و تصویری
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq ffmpeg pulseaudio

      - name: نصب کتابخونه‌های پایتون
        run: |
          pip install requests beautifulsoup4 playwright playwright-stealth

      - name: نصب مرورگرهای Playwright
        run: |
          playwright install chromium firefox
          playwright install-deps chromium firefox

      - name: اجرای ربات (۳۵۵ دقیقه) به همراه کارت صدای مجازی
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
        run: |
          # راه‌اندازی کارت صدای مجازی برای نسخه ۲۲
          pulseaudio --start --exit-idle-time=-1
          pactl load-module module-null-sink sink_name=virtual_out
          pactl set-default-sink virtual_out
          
          # اجرای ربات با محدودیت زمانی ۲۱۳۰۰ ثانیه (۳۵۵ دقیقه)
          timeout 21300 python Bot.py
